### PR TITLE
Fix for multiline blockquotes, Fixes #1

### LINKED ISSUE #1: Multi-line blocks don't render corectly.
Hello....

Thank you for publishing this plugin.  I had developed something similar for a project I am working on and encountered this same issue.

When rending multiline blockquots like:

```md
!> *Time* is money,
!> my friend!
```

The output is:

```html
<blockquote class="tip">
<p><em>Time</em> is money,
!&gt; my friend! is money,
!&gt; my friend!</p>
</blockquote>
```

Notice the `!&gt;` and repeated text.

I can do a PR when I have time.  If you want to look at this before I do here is my visitor that would need to be adapted for your project.  Notice the second visitors for the children text nodes.

```js
  function pvisitor(node) {
    const { children, data = {} } = node;
    if (children.length > 0 && children[0].type === 'text') {
      const text = children[0].value;
      if (text.slice(1, 3) === '> ') {
        const chr = text[0];
        if (chr in cls) {
          const r = new RegExp(`^\\${chr}>\\s`, 'gm');
          node.data = deepmerge(data, {
            hProperties: {
              class: cls[chr]
            }
          });
          visit(node, 'text', cld => {
            cld.value = cld.value.replace(r, ' ');
          });
        }
      }
    }
  }
```

### PR DESCRIPTION
**Pull request by Hypercubed**
Fixes #1

### CODE REVIEW

**Comment by Hypercubed** [comment]
Hi @montogeek any chance we could get this merged?

**Comment by montogeek** [comment]
Sure, sorry!

**Comment by montogeek** [comment]
Thank you!

**Comment by montogeek** [comment]
Published as 1.0.1: https://www.npmjs.com/package/remark-custom-blockquotes/v/1.0.1

**Comment by Hypercubed** [comment]
Thank you!!

**Pull request merged**
